### ISSUE TITLE
Styling: Alignment of user profile info

### ISSUE THREAD

**Issue by vegantriathlete** [DrupalCampColorado/drupalcampcolorado.org#1]
The info is just bunched together. I'm viewing this on Ubuntu 14.04 and the latest version of Chrome.
![user-profile-info-alignment](https://cloud.githubusercontent.com/assets/1111301/7013425/4ac078c0-dc76-11e4-9e19-f0ea73c1c4d8.png)

**Comment by larsdesigns** [comment]
Fixed and closing...
