### ISSUE TITLE
Styling: Alignment of taxonomy terms

### ISSUE THREAD

**Issue by vegantriathlete** [DrupalCampColorado/drupalcampcolorado.org#2]
The terms are just bunched together. I'm viewing this on Ubuntu 14.04 and the latest version of Chrome.
![taxonomy-term-alignment](https://cloud.githubusercontent.com/assets/1111301/7013441/7478d536-dc76-11e4-8fc8-c977071ae5c9.png)

**Comment by larsdesigns** [comment]
Fixed and closing...
